### ISSUE TITLE
Unable to install on iPhone 14 Pro Max. Even tho version 1.0 worked.

### ISSUE THREAD

**Issue by KBrownies** [sourcelocation/AirTroller#7]
I’m wondering why the new versions aren’t available to run on iOS 16/iPhone 14 Pro Max, When version 1.0 worked just fine? Because when I tried to sign and install the new build I get an error that pops up. Is there something you can do to make a usable updated version? That would be greatly appreciated. And I’d be more than willing to donate for a working updated version for your time and effort.

Thanks.

**Comment by sourcelocation** [comment]
Hi, what error?

**Comment by KBrownies** [comment]
> Hi, what error?

This is the error that now pops up.

`Error
The app needs to be installed either using TrollStore or on Jailbroken devices error: Error
Domain=NSCocoaErrorDomain
Code=257 "The file "mobile" couldn't be opened because vou don't have permission to view it."
UserInfo={NSURL=file:///private/var/ mobile, NSFilePath=/private/var/mobile, NSUnderlyingError=0x2830a4690 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" }}`

**Comment by haxi0** [comment]
Could u send AirDrops on v1.0?

**Comment by KBrownies** [comment]
> Could u send AirDrops on v1.0?

At one point it did show other devices.

Now for some reason it's not showing up and just keeps loading.

**Comment by BomberFish** [comment]
AFAIK you can disable the check by commenting out lines 24-28 in AirTrollerApp.swift

**Comment by sourcelocation** [comment]
`The app needs to be installed either using TrollStore or on Jailbroken devices`
